// import styles from "@/app/(beforeLogin)/_components/main.module.css";
import type { Metadata, Viewport } from "next";
import ThemeRegistry from "./_components/theme-registry";
import "./globals.css";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export async function generateMetadata(): Promise<Metadata> {
  const defaultValues = {
    APP_NAME: "연습용 프로젝트",
    APP_DEFAULT_TITLE: "연습용 프로젝트",
    APP_TITLE_TEMPLATE: "%s | 연습용 프로젝트",
    APP_DESCRIPTION: "연습용 프로젝트입니다.",
    // APP_IMAGES: "https://images.jtbc.co.kr/og_2023/news.png",
    APP_IMAGES: "/kw.jpeg",
  };
  return {
    applicationName: defaultValues.APP_NAME,
    title: {
      default: defaultValues.APP_DEFAULT_TITLE,
      template: defaultValues.APP_TITLE_TEMPLATE,
    },
    description: defaultValues.APP_DESCRIPTION,
    manifest: "/manifest.json",
    appleWebApp: {
      capable: true,
      statusBarStyle: "default",
      title: defaultValues.APP_DEFAULT_TITLE,
    },
    formatDetection: {
      telephone: false,
    },
    openGraph: {
      type: "website",
      siteName: defaultValues.APP_NAME,
      title: {
        default: defaultValues.APP_DEFAULT_TITLE,
        template: defaultValues.APP_TITLE_TEMPLATE,
      },
      description: defaultValues.APP_DESCRIPTION,
      images: [defaultValues.APP_IMAGES],
    },
    twitter: {
      card: "summary_large_image",
      site: "@jtbcnews",
      creator: defaultValues.APP_NAME,
      title: {
        default: defaultValues.APP_DEFAULT_TITLE,
        template: defaultValues.APP_TITLE_TEMPLATE,
      },
      description: defaultValues.APP_DESCRIPTION,
      images: [defaultValues.APP_IMAGES],
    },
    icons: [
      {
        rel: "apple-touch-icon",
        sizes: "57x57",
        // url: "https://nstatic.jtbc.co.kr/favicon_2023/news/apple-icon-57x57.png",
        url: "/kw.jpeg",
      },
      {
        rel: "apple-touch-icon",
        sizes: "60x60",
        // url: "https://nstatic.jtbc.co.kr/favicon_2023/news/apple-icon-60x60.png",
        url: "/kw.jpeg",
      },
      {
        rel: "apple-touch-icon",
        sizes: "72x72",
        // url: "https://nstatic.jtbc.co.kr/favicon_2023/news/apple-icon-72x72.png",
        url: "/kw.jpeg",
      },
      {
        rel: "apple-touch-icon",
        sizes: "76x76",
        // url: "https://nstatic.jtbc.co.kr/favicon_2023/news/apple-icon-76x76.png",
        url: "/kw.jpeg",
      },
      {
        rel: "apple-touch-icon",
        sizes: "114x114",
        // url: "https://nstatic.jtbc.co.kr/favicon_2023/news/apple-icon-114x114.png",
        url: "/kw.jpegng",
      },
      {
        rel: "apple-touch-icon",
        sizes: "120x120",
        // url: "https://nstatic.jtbc.co.kr/favicon_2023/news/apple-icon-120x120.png",
        url: "/kw.jpegng",
      },
      {
        rel: "apple-touch-icon",
        sizes: "144x144",
        // url: "https://nstatic.jtbc.co.kr/favicon_2023/news/apple-icon-144x144.png",
        url: "/kw.jpegng",
      },
      {
        rel: "apple-touch-icon",
        sizes: "152x152",
        // url: "https://nstatic.jtbc.co.kr/favicon_2023/news/apple-icon-152x152.png",
        url: "/kw.jpegng",
      },
      {
        rel: "apple-touch-icon",
        sizes: "180x180",
        // url: "https://nstatic.jtbc.co.kr/favicon_2023/news/apple-icon-180x180.png",
        url: "/kw.jpegng",
      },
      {
        rel: "apple-touch-icon",
        sizes: "192x192",
        // url: "https://nstatic.jtbc.co.kr/favicon_2023/news/apple-icon-192x192.png",
        url: "/kw.jpegng",
      },
      {
        rel: "icon",
        sizes: "32x32",
        // url: "https://nstatic.jtbc.co.kr/favicon_2023/news/apple-icon-32x32.png",
        url: "/kw.jpeg",
      },
      {
        rel: "icon",
        sizes: "57x57",
        // url: "https://nstatic.jtbc.co.kr/favicon_2023/news/apple-icon-57x57.png",
        url: "/kw.jpeg",
      },
      {
        rel: "icon",
        sizes: "96x96",
        // url: "https://nstatic.jtbc.co.kr/favicon_2023/news/apple-icon-96x96.png",
        url: "/kw.jpeg",
      },
      {
        rel: "icon",
        sizes: "16x16",
        // url: "https://nstatic.jtbc.co.kr/favicon_2023/news/apple-icon-16x16.png",
        url: "/kw.jpeg",
      },
    ],
  };
}

export const viewport: Viewport = {
  width: "device-width",
  userScalable: false,
  initialScale: 1,
  interactiveWidget: "resizes-content",
  themeColor: "#222",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="ko" suppressHydrationWarning={true}>
      <body>
        <ThemeRegistry>{children}</ThemeRegistry>
      </body>
    </html>
  );
};
export default RootLayout;
